language: rust
rust:
- nightly
cache: cargo
script:
- cargo build --release --verbose --all
- cargo test --release --verbose --all
- cargo test --release --verbose --all -- --ignored
services:
- mongodb
- docker
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
before_install:
  - base=https://github.com/docker/machine/releases/download/v0.16.0 && curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine && sudo install /tmp/docker-machine /usr/local/bin/docker-machine
  - docker-machine --version
before_deploy:
  - bash deploy-scripts/deploy.sh
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: podcastrs-deploy
  acl: public_read
  region: ca-central-1
  local_dir: deployment
  skip_cleanup: true
  on:
    repo: DenysPolitiuk/podcastrs
    branch: dev
