language: rust
rust:
- nightly
cache: cargo
script:
- cargo build --verbose --all
- cargo test --verbose --all
- cargo test --verbose --all -- --ignored
services:
- mongodb
deploy:
  provider: s3
  access_key_id: AKIA2CLQD4VJLSGGLL4Q
  secret_access_key:
    secure: "knOwWAPqVzGa8svFE+bi+ayOwa9Wyc/TjK4CPKmgxbvRfr1x0mYVowpBTGAA/dKotO8A4JLaIiArnN8mJtFCrrL8njWV7nDhqwxZ1Qm5BmArEfrCpmv542snsWez6eu3jgSZv2n1y4MdWFMIJDLqCb7zceIUyoSJzax3NcXG6U/3QlQXw/vqzSVawnTxdyfDcW/GzsPffCIk3bABeXblZEnLOX6iSkJfyDs63SARrZPE+UyiYJG1KTNlMNmu2rorfk8fe8iuaUearM73B7WrLOe2qO0aUJ6eMWP99d1b5P8FMhhMPHr6KRW2Gma2+GfXG1ig1KowBZ6SgBlwuozxkty4dJiqfCC8z5A1Jsqj1RUbcARfT08486ts1UmzRnFnHnmFH084B5shMr7VPjGH4u+yJ3Y84LepU+pyv9Zwuk2gMKZd24R5RPnSdwv6JDM2x1/8hEz8vUQrWwjqM5w0D3fxm/1DmTDjpdIC7RwpqMzaGCHd3TPESlRbtERmhoze3ZgDgSxvB04D7MVgrRgZMXfVSaoMwU3QE8hB0OjRQIEL64zTqYgPhtSwNqNuMaB25RZ137WWIL3ERCt5MmgcIP6n/psdWJO4PnXxzvcNa3MEc85wiDNhLZpBnZK/Pz8vA9W50ZZWT2XKeyU/gQQjtAz6Kr6tNly5WD/4EORiKmo="
  bucket: podcastrs-deploy
  region: "ca-central-1"
  skip_cleanup: true
  on:
    repo: DenysPolitiuk/podcastrs
    branch: dev
