---
language: rust
rust:
        - nightly
cache: cargo
script:
        - cargo build --verbose --all
        - cargo test --verbose --all
        - cargo test --verbose --all -- --ignored
services:
        - mongodb
deploy:
        on:
                all_branches: true
                condition: "$TRAVIS_BRANCH =~ ^(dev|master)$"
        provider: s3
        access_key_id: "AKIA2CLQD4VJLSGGLL4Q"
        bucket: "podcastrs-deploy"
        skip_cleanup: true
        secret_access_key:
                secure: "ySV1wa2I/sY2FvdD9Tb4mf7OtlOEPYIVZwT+3m5D3Oy/2Pft1yIZZT1vUQpifX2oeFyMCPPKjLcWFRgEKsuwvWmrsomI5QRyXPm5wM22VPPApzHgB+z3CJcZY0fI5dx+JsauK6BWlsQgryN0KNMKnfFL++PXhfiZNOoaWUmuzJqz3lA7FaTdEPdItEwQdG0k3S8PR2ZLbFkXrCb43l1bbMfyAdnEFIgwmwj5fTrc/rqwpYddgoV3MTV6E4kXG1l8q+ZdGDEB4iLv78shUCaGTIvNgpYSjRsCAkXNEQCE8q8H3cteXBqQ6RT1DpKRZBKIl5EdFz6mu2ue9NNko30y8Bcrkqr36/wzmy2nq6Wa0GTMuod56XMGT6QCB7Zrgz11dB7xDS42qtkQcYL3je7A/rLDJg/1VZQuWyhrwap7EGIiHi95DwC/mmZoMivzJnntoOyrh17uurB7D6sKc5qHH8eXtg9zMNPOvbJK6XnWG4KnT49OTUMfzBGMdhAOMSbtPPl9cgnDlvaVoVLNO9rIGIjQ2kGOPseSok6sdNKMjdxKAFJSpntTZA2R+MTkS2hnNILoqldQ4ZL3eZnZYZuCmCtRyk8QikdqEcqdxSaojIMzoXG2McsCBGVZYrQQl8N2Gmi0ny+Fq7B4PXJ9OHo331RDvR2jmukZIHYRuZqDRv0="
