language: rust
rust:
- nightly
cache: cargo
script:
- cargo build --verbose --all
- cargo test --verbose --all
- cargo test --verbose --all -- --ignored
services:
- mongodb
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: podcastrs-deploy
  acl: public_read
  region: ca-central-1
  on:
    repo: DenysPolitiuk/podcastrs
    branch: dev
