language: rust
rust:
- nightly
cache: cargo
script:
- cargo build --verbose --all
- cargo test --verbose --all
- cargo test --verbose --all -- --ignored
- cargo build --release --verbose --all
services:
- mongodb
before_deploy:
  - bash dev-scripts/deploy.sh
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: podcastrs-deploy
  acl: public_read
  region: ca-central-1
  local_dir: deployment
  skip_cleanup: true
  on:
    repo: DenysPolitiuk/podcastrs
    branch: dev
