language: rust
rust:
- nightly
cache: cargo
script:
- cargo build --verbose --all
- cargo test --verbose --all
- cargo test --verbose --all -- --ignored
services:
- mongodb
deploy:
  provider: s3
  access_key_id: AKIA2CLQD4VJLSGGLL4Q
  secret_access_key:
    secure: "N214RAhLgKKubmqWSmfd2cNT8I86l9SbZg2WtM5f4RteyutaRyRr50AhB0IKruUE525aoEy68Yjuzwuf7GwPaHOGuVlEI5JKT6LFo4tEAPGdy5B5RwHxvl/+TSpP58kcRde0kkNp/G31sevimL6bUNdJHGlzaO/l6YPV70L1isGZl8zXyhuVIi4DSwUTdeFwQR3XJAyFNQrPQqYEP4KU0Th8yxiKaYPsrGA+9jjL/1h34H6jcciCuZoDX53Xf0zQRYvkuBB7Z086mCgF3JLML+BqrOJf/L0DKvezQskDM3X4EnmJSIqSPIFbvTrawwdq0Bwtvf+o677QnoasV09TOkXz+q2tdZGn6yHLNaHfOP6vu3rvCaZVZm8qe+l93qQB4RA+yM6NJNtFgO8yEP69nBtoTSwEHBX7ex5oUNgikk4hSNrPJ6Ors6FxbXLitlxlr4Fenns5dCtbeYAoeqyulSNUDd+YEH4vyRUmBC7hOXaxsmoEaKBoBsN1hdOZtKzHHOgo7183vtBo8lu8ruCKl5jlXeLm18tihMgPpN7bnLu74AEdZuJmVzTWDGHGwtUcbxgfQ/P26tIm/NomfKzzL/BfWc/OdVFjHoFnpMPmbWSP6hydHTqWgXTgbF5/GM1FElKuIhs4OGjDI94sr/5K+ua0Yt8K9OTRWMNcgL5ame8="
  bucket: podcastrs-deploy
  region: ca-central-1
  skip_cleanup: true
  acl: public_read
  on:
    repo: DenysPolitiuk/podcastrs
    branch: dev
