language: rust
rust:
- nightly
cache: cargo
script:
- cargo build --verbose --all
- cargo test --verbose --all
- cargo test --verbose --all -- --ignored
services:
- mongodb
deploy:
  provider: s3
  access_key_id: AKIA2CLQD4VJLSGGLL4Q
  secret_access_key:
    secure: ZfGoauZr+CedH/XsuXDHvgVaC2T71cam0y9cGn5OdWQthjBgMAWzd9/V/WAFfjrnE6R8pa7+F6qoaeZNgAGqWgRB7mNEZ8h1k6eoS6OA/v03v+Mr9CcUOnqqFVbIi2jdYtKw1n4wf/a7mjnnnNxTiRxq6xbW7Z5WcPQChNWXx4xwjMtBEOLcJ99pubYW5REUjPdqk2SGK1/X+V401bKTW+Q+ooFdenDax7ZE5Phx5uXPorP9/8rF1CAbNQU26bmfhqqUghdmkr6MPeUUX+qrFuSvnhA/yL+5tmiAQA8lUMlECrI7VcihghKgCUjavlEXpQt3dsqq4OWGozAY9gMm24GhjiyYKv63j2XYrHki/HCKZkouw8kwcuvDDYWEDQalFDXfd3q8ru0jCpxqPCMg4xfUnTAcV1sQm8IK9KagYe5JQuZTfHph0Ht8tACr3PqwPkQTEifp7+YzMUCqFXJReCMggayf7c4l6B0NTgEharmhpuDKpn+j6pJzBGmnmDomvjEcEEi2nDn3ARCEt3EzL+mHdodTB82CK+eX14LT53a+ENrFuUVjkBXiIQKr8NrZmF0ArcTOqmbCrGozQNpjaxp+Jecvg8uSbFDMKXM+I9QMnaUpLaHltMXB3ibQ/u7nXNVOXE9yCMcKJgB8ThOLocIGb2rb38JelQGimfLrbck=
  bucket: podcastrs-deploy
  acl: ''
  on:
    repo: DenysPolitiuk/podcastrs
    branch: dev
