[package]
name = "podcastrs"
version = "0.1.0"
authors = ["boris"]
edition = "2018"

[dependencies]
reqwest = "0.9.19"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rss]
version = "1.8"
